### ISSUE TITLE
make

### ISSUE THREAD

**Issue by brucelane** [titi38/libnavajo#1]
hi,
I got an error when running make:
![screenshot from 2015-12-15 03 58 56](https://cloud.githubusercontent.com/assets/138158/11800852/b1ca4e3e-a2e0-11e5-96d3-1ea2085b3ac2.png)
any hint?

**Comment by titi38** [comment]
Hi,
You need to install the "pam-devel" package to build libnavajo. (the
package could be called "lib_pam_0g-dev" in your distro)
Cheers
Thierry

2015-12-15 4:03 GMT+01:00 Bruce LANE notifications@github.com:

**Comment by brucelane** [comment]
yes it works!
merci
