### ISSUE TITLE
On the fly page creation

### ISSUE THREAD

**Issue by spelle** [titi38/libnavajo#11]
Hello Thierry :-)

me, again ;-)

According to this page (https://en.wikipedia.org/wiki/Representational_state_transfer) for a POST within a collection, a new entry is created and then returned.

This is what i do :
`m_dr.add( ssUrl.str(), new restKeySetPage( m_db, keySetId, m_dr ) ) ;`
`response->forwardTo( ssUrl.str() ) ;`

However, I get a 404.

I wondering if there is a kind of delay between the page creation and its availability ?

Thanks a lot.

**Comment by titi38** [comment]
Hello Sebastien,
I'm not sure I understand again ;-)
"m_dr" is one of your dynamic repositories ? Have you added it to the webserver ?
Why are you using "forwardTo" ?
Cheers

**Comment by spelle** [comment]
Hello :-)

Yes, `m_dr` is a dynamic repository (a reference in fact). It's been added to the webserver at the initialisation. This is the sole dynamic repository I have.

I use `forwardTo` in order to answer with the newly created page. I could saw this within one of the example.

Cheers,

**Comment by titi38** [comment]
Hello Sebastien,
Sorry for the delay, I am currently on vacation.
Indeed, it should work... Could you send me a complete example, that I can compile and run ? (thierry.descombes@gmail.com)
And I will add you a function to remove a page from a dynamic repository. If I understand correctly, It would be usefull, right ? Cheers

**Comment by spelle** [comment]
Hello Thierry,

No worries. Thanks for the time you already spent ^_^

I sent you a mail with the complete project.

A function which removes a page can be usefull, yes ; but, isn't the freefile function meant to do this ? However, since we are building a key-generation oracle, we do not plan to allow the deletion of a keySet. If we have to do it, we will delete it into the database.

Cheers

**Comment by titi38** [comment]
The bug has been fixed.
