### ISSUE TITLE
Big file on LocalRepository

### ISSUE THREAD

**Issue by beziarum** [titi38/libnavajo#13]
Hi,

It seems that the class LocalRepository doesn't support large files (a .png of more than 10MB for example) on server with a little of latency. I have noticed that it works fine on local but not with a distant server.
The image began to load but stopped after a while and the server printed this trace  :
[2017-03-26 15:05:33] >  Webserver: httpSend failed sending the page: data/153610754_0_Displayed.png

**Comment by titi38** [comment]
Hello,
It's weird. I will do some more tests... Could you send me a capture of the traffic in pcap format? (Using tcpdump or wireshark)
My email is thierry.descombes@gmail.com. Thanks a lot.
Cheers

**Comment by titi38** [comment]
The default timeout for socket was too short ! It has been fixed in version 1.5
