### ISSUE TITLE
Two warnings appeared during the compilation of the library

### ISSUE THREAD

**Issue by ghost** [titi38/libnavajo#14]
Hi,

I really love your library. I use it for my own purpose and I appreciate the easy way to create interactive webpage with libnavajo through C++ application.

I just report two warnings: `~/Downloads/libnavajo-master/src/WebServer.cc: In member function ‘void WebServer::threadProcessing()’:
~/Downloads/libnavajo-master/src/WebServer.cc:1465: warning: dereferencing pointer ‘clientAddress.417’ does break strict-aliasing rules
~/Downloads/libnavajo-master/src/WebServer.cc:1465: note: initialized from here

~/Downloads/libnavajo-master/src/WebServer.cc:1471: warning: dereferencing pointer ‘clientAddress.418’ does break strict-aliasing rules
~/Downloads/libnavajo-master/src/WebServer.cc:1471: note: initialized from here`

These warnings appeared during the compilation of the library. There are not critical. I'm using GCC 4.4.7 on CentOs 7.

**Comment by titi38** [comment]
Fixed. Cheers
