### ISSUE TITLE
Crash when access the server through https

### ISSUE THREAD

**Issue by dima077** [titi38/libnavajo#16]
Hi,

The issue is related to WebServer::**setUseSSL** method.

If the certificate in the parameter to the method above **is not signed by CA** and you try to access the server through https in the browser the very first time, the message stating that "The owner of .... has configured their website improperly" appears in the web browser. In that same moment **libnavajo crashes** with "**Broken pipe**" exception. If you add security exception in the browser, and run the server again, it works fine.

That crash happens very **consistently** each time.

https://gyazo.com/cdeb802178501e3a2728798ca3facc17

Thanks for help!

Regards,
Dima.

**Comment by titi38** [comment]
Hi,
It should work now. Could you pull the last version and try again ? Thanks a lot
Cheers
