### ISSUE TITLE
Http response error can't be different of 404

### ISSUE THREAD

**Issue by jcourtat** [titi38/libnavajo#17]
Hello, 
thanks for you work on this library.
I don't see how to build a response with the error code i want and the content i want.
when i return false in the getPage() method, libnavajo automatically set HTTP error code to 404 and a default body with HTML is set in the body response.
Am i right ?
If this is the case, would you agree on a patch permitting such configuration ?

regards

Julien

**Comment by titi38** [comment]
Hello,
It's a very relevant remark. I will add soon a method into the HttpResponse object to set the http return code (default 200). Thus, you will be able to return the page you want, with the http code of your dream ;-)
I'll close the ticket as soon as it will be fully implemented and tested.
Cheers
Thierry

**Comment by titi38** [comment]
Hi,

I just push a new version that should do the job.

2 new methods are available in the httpResponse:
void setHttpReturnCode(unsigned value, const std::string message)
and
void setHttpReturnCode(unsigned value) // for standart http return code (the message is guest by searching through a given list of official return codes)

By default, http return code is set to 200, and message is "OK"...

Cheers,
Thierry

**Comment by jcourtat** [comment]
Hello, thank you for your work!
I may be wrong, but after removing an url using dynamicRepository->remove(url), i can still access it and enter code within getPage().
Before your enhancement, it was responding error 404 which was the good code, and did not enter getPage().

regards

Julien

**Comment by titi38** [comment]
Hello,
You were right ! It should be fixed... Could you confirm ? Thanks a lot...
Cheers,
