### ISSUE TITLE
Valgrind report

### ISSUE THREAD

**Issue by ghost** [titi38/libnavajo#19]
I just create a simple libnavajo program to show you some issues foudn by valgrind, there are:
- Memory leaks
- Invalid write
- Invalid read

Valgrind report:
> ==8915== Memcheck, a memory error detector
> ==8915== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==8915== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
> ==8915== Command: ./LibnavajoTest
> ==8915== 
> [2017-07-24 10:40:54] >  WebServer: Service is starting !
> New Websocket from host '10.1.38.22' - socketId=6
> ==8915== Thread 67:
> ==8915== Invalid write of size 1
> ==8915==    at 0x41F663: WebSocketClient::receivingThread() (WebSocketClient.cc:242)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Address 0x4e3750b is 0 bytes after a block of size 11 alloc'd
> ==8915==    at 0x4A073AC: realloc (vg_replace_malloc.c:784)
> ==8915==    by 0x4215EE: nvj_gunzip_websocket_v2(unsigned char**, unsigned char const*, unsigned long, bool, unsigned char*, unsigned int*, unsigned int) (nvjGzip.h:331)
> ==8915==    by 0x41F64F: WebSocketClient::receivingThread() (WebSocketClient.cc:237)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915== 
> Message: 'testMessage' received from host '10.1.38.22'
> ^C[2017-07-24 10:41:02] >  WebServer: Service is stopping !
> pthread_join(): Unknown error
> ==8915== Invalid write of size 1
> ==8915==    at 0x41F28A: WebSocketClient::receivingThread() (WebSocketClient.cc:138)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Address 0x4dc6a10 is 33,072 bytes inside a block of size 33,104 free'd
> ==8915==    at 0x4A0677A: operator delete(void*) (vg_replace_malloc.c:574)
> ==8915==    by 0x420C75: WebSocketClient::closeWS() (WebSocketClient.cc:314)
> ==8915==    by 0x40E650: removeAllClients (WebSocket.hh:231)
> ==8915==    by 0x40E650: WebServer::exit() (WebServer.cc:1201)
> ==8915==    by 0x4077F3: WebServer::stopService() (WebServer.hh:269)
> ==8915==    by 0x4064F9: exitFunction(int) (main.cpp:11)
> ==8915==    by 0x3B30E3250F: ??? (in /lib64/libc-2.12.so)
> ==8915==    by 0x3B3120EC29: recv (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x41F273: WebSocketClient::receivingThread() (WebSocketClient.cc:133)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Block was alloc'd at
> ==8915==    at 0x4A07DB5: operator new(unsigned long) (vg_replace_malloc.c:332)
> ==8915==    by 0x416F30: newConnectionRequest (WebSocket.hh:214)
> ==8915==    by 0x416F30: WebServer::accept_request(ClientSockData*, bool) (WebServer.cc:648)
> ==8915==    by 0x417486: WebServer::poolThreadProcessing() (WebServer.cc:1431)
> ==8915==    by 0x41D4D8: WebServer::startPoolThread(void*) (WebServer.hh:71)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915== 
> ==8915== Invalid read of size 1
> ==8915==    at 0x41EF27: WebSocketClient::receivingThread() (WebSocketClient.cc:120)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Address 0x4dc6a10 is 33,072 bytes inside a block of size 33,104 free'd
> ==8915==    at 0x4A0677A: operator delete(void*) (vg_replace_malloc.c:574)
> ==8915==    by 0x420C75: WebSocketClient::closeWS() (WebSocketClient.cc:314)
> ==8915==    by 0x40E650: removeAllClients (WebSocket.hh:231)
> ==8915==    by 0x40E650: WebServer::exit() (WebServer.cc:1201)
> ==8915==    by 0x4077F3: WebServer::stopService() (WebServer.hh:269)
> ==8915==    by 0x4064F9: exitFunction(int) (main.cpp:11)
> ==8915==    by 0x3B30E3250F: ??? (in /lib64/libc-2.12.so)
> ==8915==    by 0x3B3120EC29: recv (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x41F273: WebSocketClient::receivingThread() (WebSocketClient.cc:133)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Block was alloc'd at
> ==8915==    at 0x4A07DB5: operator new(unsigned long) (vg_replace_malloc.c:332)
> ==8915==    by 0x416F30: newConnectionRequest (WebSocket.hh:214)
> ==8915==    by 0x416F30: WebServer::accept_request(ClientSockData*, bool) (WebServer.cc:648)
> ==8915==    by 0x417486: WebServer::poolThreadProcessing() (WebServer.cc:1431)
> ==8915==    by 0x41D4D8: WebServer::startPoolThread(void*) (WebServer.hh:71)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915== 
> ==8915== Invalid read of size 1
> ==8915==    at 0x41EF33: WebSocketClient::receivingThread() (WebSocketClient.cc:147)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Address 0x4dc6a10 is 33,072 bytes inside a block of size 33,104 free'd
> ==8915==    at 0x4A0677A: operator delete(void*) (vg_replace_malloc.c:574)
> ==8915==    by 0x420C75: WebSocketClient::closeWS() (WebSocketClient.cc:314)
> ==8915==    by 0x40E650: removeAllClients (WebSocket.hh:231)
> ==8915==    by 0x40E650: WebServer::exit() (WebServer.cc:1201)
> ==8915==    by 0x4077F3: WebServer::stopService() (WebServer.hh:269)
> ==8915==    by 0x4064F9: exitFunction(int) (main.cpp:11)
> ==8915==    by 0x3B30E3250F: ??? (in /lib64/libc-2.12.so)
> ==8915==    by 0x3B3120EC29: recv (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x41F273: WebSocketClient::receivingThread() (WebSocketClient.cc:133)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Block was alloc'd at
> ==8915==    at 0x4A07DB5: operator new(unsigned long) (vg_replace_malloc.c:332)
> ==8915==    by 0x416F30: newConnectionRequest (WebSocket.hh:214)
> ==8915==    by 0x416F30: WebServer::accept_request(ClientSockData*, bool) (WebServer.cc:648)
> ==8915==    by 0x417486: WebServer::poolThreadProcessing() (WebServer.cc:1431)
> ==8915==    by 0x41D4D8: WebServer::startPoolThread(void*) (WebServer.hh:71)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915== 
> ==8915== Invalid read of size 1
> ==8915==    at 0x41EEA0: WebSocketClient::receivingThread() (WebSocketClient.cc:108)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Address 0x4dc6a10 is 33,072 bytes inside a block of size 33,104 free'd
> ==8915==    at 0x4A0677A: operator delete(void*) (vg_replace_malloc.c:574)
> ==8915==    by 0x420C75: WebSocketClient::closeWS() (WebSocketClient.cc:314)
> ==8915==    by 0x40E650: removeAllClients (WebSocket.hh:231)
> ==8915==    by 0x40E650: WebServer::exit() (WebServer.cc:1201)
> ==8915==    by 0x4077F3: WebServer::stopService() (WebServer.hh:269)
> ==8915==    by 0x4064F9: exitFunction(int) (main.cpp:11)
> ==8915==    by 0x3B30E3250F: ??? (in /lib64/libc-2.12.so)
> ==8915==    by 0x3B3120EC29: recv (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x41F273: WebSocketClient::receivingThread() (WebSocketClient.cc:133)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915==  Block was alloc'd at
> ==8915==    at 0x4A07DB5: operator new(unsigned long) (vg_replace_malloc.c:332)
> ==8915==    by 0x416F30: newConnectionRequest (WebSocket.hh:214)
> ==8915==    by 0x416F30: WebServer::accept_request(ClientSockData*, bool) (WebServer.cc:648)
> ==8915==    by 0x417486: WebServer::poolThreadProcessing() (WebServer.cc:1431)
> ==8915==    by 0x41D4D8: WebServer::startPoolThread(void*) (WebServer.hh:71)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915== 
> ==8915== 
> ==8915== HEAP SUMMARY:
> ==8915==     in use at exit: 40,992 bytes in 74 blocks
> ==8915==   total heap usage: 356 allocs, 282 frees, 2,132,562 bytes allocated
> ==8915== 
> ==8915== Thread 1:
> ==8915== 30 bytes in 1 blocks are definitely lost in loss record 4 of 11
> ==8915==    at 0x4A071BA: malloc (vg_replace_malloc.c:298)
> ==8915==    by 0x41D8CD: WebSocketClient::sendTextMessage(std::string const&, bool) (WebSocketClient.cc:440)
> ==8915==    by 0x408117: WebSocket::sendBroadcastTextMessage(std::string const&, bool) (WebSocket.hh:120)
> ==8915==    by 0x40837D: MyWebSocket::onTextMessage(WebSocketClient*, std::string const&, bool) (main.cpp:25)
> ==8915==    by 0x41FA03: WebSocketClient::receivingThread() (WebSocketClient.cc:255)
> ==8915==    by 0x421B48: WebSocketClient::startReceivingThread(void*) (WebSocketClient.hh:63)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915== 
> ==8915== 608 bytes in 1 blocks are possibly lost in loss record 9 of 11
> ==8915==    at 0x4A05F1F: calloc (vg_replace_malloc.c:710)
> ==8915==    by 0x3B30611D02: _dl_allocate_tls (in /lib64/ld-2.12.so)
> ==8915==    by 0x3B312072CC: pthread_create@@GLIBC_2.2.5 (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x41E5EE: create_thread (nvjThread.h:63)
> ==8915==    by 0x41E5EE: startWebSocketThreads (WebSocketClient.hh:78)
> ==8915==    by 0x41E5EE: WebSocketClient::WebSocketClient(WebSocket*, HttpRequest*) (WebSocketClient.cc:33)
> ==8915==    by 0x416F41: newConnectionRequest (WebSocket.hh:214)
> ==8915==    by 0x416F41: WebServer::accept_request(ClientSockData*, bool) (WebServer.cc:648)
> ==8915==    by 0x417486: WebServer::poolThreadProcessing() (WebServer.cc:1431)
> ==8915==    by 0x41D4D8: WebServer::startPoolThread(void*) (WebServer.hh:71)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915== 
> ==8915== 38,912 bytes in 64 blocks are possibly lost in loss record 11 of 11
> ==8915==    at 0x4A05F1F: calloc (vg_replace_malloc.c:710)
> ==8915==    by 0x3B30611D02: _dl_allocate_tls (in /lib64/ld-2.12.so)
> ==8915==    by 0x3B312072CC: pthread_create@@GLIBC_2.2.5 (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x4073DE: create_thread(unsigned long*, void* (*)(void*), void*, bool, unsigned long) (nvjThread.h:63)
> ==8915==    by 0x40E543: WebServer::initPoolThreads() (WebServer.cc:1447)
> ==8915==    by 0x4127D3: WebServer::threadProcessing() (WebServer.cc:1486)
> ==8915==    by 0x4131B8: WebServer::startThread(void*) (WebServer.cc:1463)
> ==8915==    by 0x3B31207AA0: start_thread (in /lib64/libpthread-2.12.so)
> ==8915==    by 0x3B30EE8BCC: clone (in /lib64/libc-2.12.so)
> ==8915== 
> ==8915== LEAK SUMMARY:
> ==8915==    definitely lost: 30 bytes in 1 blocks
> ==8915==    indirectly lost: 0 bytes in 0 blocks
> ==8915==      possibly lost: 39,520 bytes in 65 blocks
> ==8915==    still reachable: 1,442 bytes in 8 blocks
> ==8915==                       of which reachable via heuristic:
> ==8915==                         stdstring          : 58 bytes in 2 blocks
> ==8915==         suppressed: 0 bytes in 0 blocks
> ==8915== Reachable blocks (those to which a pointer was found) are not shown.
> ==8915== To see them, rerun with: --leak-check=full --show-leak-kinds=all
> ==8915== 
> ==8915== For counts of detected and suppressed errors, rerun with: -v
> ==8915== ERROR SUMMARY: 8 errors from 8 contexts (suppressed: 8 from 5)

Program used: 
```
#include <signal.h> 
#include <string.h> 
#include "libnavajo/libnavajo.hh"
#include "libnavajo/WebSocket.hh"
#include "libnavajo/LogStdOutput.hh"

WebServer *webServer = NULL;

void exitFunction( int )
{
  if (webServer != NULL) webServer->stopService();
}

class MyWebSocket : public WebSocket
{
  bool onOpening(HttpRequest* request)
  {
    printf ("New Websocket from host '%s' - socketId=%d\n", request->getPeerIpAddress().str().c_str(), request->getClientSockData()->socketId);
    return true;
  }

  void onTextMessage(WebSocketClient* client, const std::string &message, const bool)
  {
    printf ("Message: '%s' received from host '%s'\n", message.c_str(), client->getHttpRequest()->getPeerIpAddress().str().c_str());
    sendBroadcastTextMessage("The message has been received!");
  };
} myWebSocket;

class MyDynamicPage: public DynamicPage
{
  bool getPage(HttpRequest*, HttpResponse *response)
  {
    response->forwardTo("index.html");

    return true;
  }
};


int main()
{
  // connect signals
  signal( SIGTERM, exitFunction );
  signal( SIGINT, exitFunction );
  
  NVJ_LOG->addLogOutput(new LogStdOutput);

  webServer = new WebServer;

  webServer->setServerPort(8080);
  webServer->startService();

  webServer->addWebSocket("test", &myWebSocket);

  LocalRepository localRep("", "./html");

  MyDynamicPage page;
  DynamicRepository myRepo;
  myRepo.add("index.html", &page); // unusual html extension for a dynamic page !

  webServer->addRepository(&localRep);
  webServer->addRepository(&myRepo);

  webServer->wait();
  
  LogRecorder::freeInstance();
  return 0;
}
```

Test on Centos 6 with latest libnavajo code.

**Comment by titi38** [comment]
Hello,
I am not sure that valgrind works correctly with multithreading...
Anyway, if you think there's a memory leak, could you try to introspect ? I don't think it's possible that the leak is significant in running condition (Many services use libnavajo and run for months without interruption now... and especially on Raspberry embedded cards with few resources)
But maybe everything isn't properly released when the websocket destructor is called... 
I took a look, but the sequence of operations is quite complicated.
Cheers
