### ISSUE TITLE
make problem with examples

### ISSUE THREAD

**Issue by njournet** [titi38/libnavajo#2]
Hi!

I have a problem for linking 1_basic, 3_websoket 4_wschat (2_gauge works fine)

![libnavajo-error](https://cloud.githubusercontent.com/assets/16337285/11871066/2a795da0-a4cd-11e5-86ec-9a573be2c21e.png)

my config : 
Yosemit 10.10.5
clang 7.0.2
make 3.81

regards!

**Comment by titi38** [comment]
Hi,
Could you copy/paste the error ? (I can't see your screen capture...)
Thanks a lot. Cheers

2015-12-17 14:49 GMT+01:00 njournet notifications@github.com:

**Comment by njournet** [comment]
salut (je pense qu’on peut discuter en Francais :) )

Vraiment super projet ! 
Je suis enseignant-chercheur sur Bordeaux et j’ai bien envie d’utiliser votre plateforme pour faire quelques protos.

l’erreur copier/coller est en dessous.

A+

nicholas

info-njournet:1_basic njournet$ make
Generate Cpp files from HTML repository
../../bin/navajoPrecompiler exampleRepository >> PrecompiledRepository.cc ; cd ..
/bin/sh: ../../bin/navajoPrecompiler: No such file or directory
g++ -c PrecompiledRepository.cc -o PrecompiledRepository.o -O3  -Wdeprecated-declarations -I. -I/usr/local/Cellar/openssl/1.0.1j/include -I../../include -D__darwin__ -D__x86__ -fPIC -fno-common -D_REENTRANT
g++ -c example.cc -o example.o -O3  -Wdeprecated-declarations -I. -I/usr/local/Cellar/openssl/1.0.1j/include -I../../include -D__darwin__ -D__x86__ -fPIC -fno-common -D_REENTRANT
rm -f example
g++ -Wall -Wno-unused -O3 -o example PrecompiledRepository.o example.o  -lnavajo -L../../lib -lz  -L/usr/local/Cellar/openssl/1.0.1j/lib -lssl -lcrypto -lpam
ld: warning: directory not found for option '-L../../lib'
ld: warning: directory not found for option '-L/usr/local/Cellar/openssl/1.0.1j/lib'
Undefined symbols for architecture x86_64:
  "PrecompiledRepository::initIndexMap()", referenced from:
      PrecompiledRepository::PrecompiledRepository(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in example.o
  "PrecompiledRepository::indexMap", referenced from:
      _main in example.o
      PrecompiledRepository::~PrecompiledRepository() in example.o
      PrecompiledRepository::PrecompiledRepository(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in example.o
      PrecompiledRepository::getFile(HttpRequest_, HttpResponse_) in example.o
      PrecompiledRepository::~PrecompiledRepository() in example.o
  "PrecompiledRepository::location", referenced from:
      PrecompiledRepository::PrecompiledRepository(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in example.o
      PrecompiledRepository::getFile(HttpRequest_, HttpResponse_) in example.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [example] Error 1

**Comment by brucelane** [comment]
les meilleurs codeurs sont français ;-)

**Comment by titi38** [comment]
Hi Nicholas,

On macosx systems , the version of the openssl library is older , and it is not standard. You must install the homebrew package ( brew.sh )

brew install openssl

Then it is not pretty (I'll improve that...) , you must edit the Makefile by hand to use the right version :
ls / usr / local / Cellar / openssl

In the example makefile , I'll had to update LIBSSL_DIR variable definition to contain the full path
of the library you want to use .

Cheers
Thierry

> salut (je pense qu’on peut discuter en Francais :) )
> 
> Vraiment super projet !
> Je suis enseignant-chercheur sur Bordeaux et j’ai bien envie d’utiliser
> votre plateforme pour faire quelques protos.
> 
> l’erreur copier/coller est en dessous.
> 
> A+
> 
> nicholas
> 
> info-njournet:1_basic njournet$ make
> Generate Cpp files from HTML repository
> ../../bin/navajoPrecompiler exampleRepository >> PrecompiledRepository.cc
> ; cd ..
> /bin/sh: ../../bin/navajoPrecompiler: No such file or directory
> g++ -c PrecompiledRepository.cc -o PrecompiledRepository.o -O3
> -Wdeprecated-declarations -I. -I/usr/local/Cellar/openssl/1.0.1j/include
> -I../../include -D__darwin__ -D__x86__ -fPIC -fno-common -D_REENTRANT
> g++ -c example.cc -o example.o -O3 -Wdeprecated-declarations -I.
> -I/usr/local/Cellar/openssl/1.0.1j/include -I../../include -D__darwin__
> -D__x86__ -fPIC -fno-common -D_REENTRANT
> rm -f example
> g++ -Wall -Wno-unused -O3 -o example PrecompiledRepository.o example.o
> -lnavajo -L../../lib -lz -L/usr/local/Cellar/openssl/1.0.1j/lib -lssl
> -lcrypto -lpam
> ld: warning: directory not found for option '-L../../lib'
> ld: warning: directory not found for option
> '-L/usr/local/Cellar/openssl/1.0.1j/lib'
> Undefined symbols for architecture x86_64:
> "PrecompiledRepository::initIndexMap()", referenced from:
> PrecompiledRepository::PrecompiledRepository(std::__1::basic_string<char,
> std::__1::char_traits<char>, std::__1::allocator<char> > const&) in
> example.o
> "PrecompiledRepository::indexMap", referenced from:
> _main in example.o
> PrecompiledRepository::~PrecompiledRepository() in example.o
> PrecompiledRepository::PrecompiledRepository(std::__1::basic_string<char,
> std::__1::char_traits<char>, std::__1::allocator<char> > const&) in
> example.o
> PrecompiledRepository::getFile(HttpRequest_, HttpResponse_) in example.o
> PrecompiledRepository::~PrecompiledRepository() in example.o
> "PrecompiledRepository::location", referenced from:
> PrecompiledRepository::PrecompiledRepository(std::__1::basic_string<char,
> std::__1::char_traits<char>, std::__1::allocator<char> > const&) in
> example.o
> PrecompiledRepository::getFile(HttpRequest_, HttpResponse_) in example.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
> make: **\* [example] Error 1
>

**Comment by Chempa** [comment]
In my case the problem was that, the path navajoPrecompiler was wrong. Check the makefile the example you are working with.
find the line that matches the below
NAVAJO_PRECOMPILER_EXEC = ../../bin/navajoPrecompiler
make sure the path is right. 
You can leave the navajoPrecompiler in any of the bin directories and just replace the path with just navajoPrecompiler.
