### ISSUE TITLE
OPTIONS support

### ISSUE THREAD

**Issue by dgruhl** [titi38/libnavajo#26]
In order to support CORS for most browsers it would be great if METHOD OPTIONS support were included. Otherwise the setCORS doesn't work with most modern browsers.

Thanks!

**Comment by dgruhl** [comment]
Adding to HttpRequest.hh

 OPTIONS_METHOD = 7

and to WebServer.cc

                  if (strncmp(bufLine+j, "OPTIONS", 7) == 0)
                    { requestMethod=OPTIONS_METHOD; isQueryStr=true; j+=7; }

Seems to be all it takes. Open question if CORS should be added to the header even when body is null. Also, 204 returns seem to confuse some pre-flight checks (so perhaps it should always be 200?). The workaround is to set the return content to something like "200".

**Comment by titi38** [comment]
Thanks ! It's commited.
Concerning the return code, I will look more closely. Have you check the behavior of others webservers (Apache, I2S, ...) ? Cheers

**Comment by dgruhl** [comment]
Thank you!!! I was playing with Restify - the hack there is to return content of "200" (the three byte string) to make it work. This may be the best approach - it just might be worth documenting.

As to if CORS headers should be returned with 204's I am not seeing anything in the RFC either way. I suspect it wouldn't HURT to have them in (they are just random headers otherwise). Any reason not to include them on a 204? (I can see on a 3xx or 4xx error, but on a 2xx success?)

**Comment by titi38** [comment]
The success code (204) was determined dynamically according to the response to the request (like some http others errors).

I have now upgraded the behavior: you can force a return code using the 2 methods of HttpResponse:
  void setHttpReturnCode(const unsigned value)
  void setHttpReturnCode(const unsigned value, const std::string message) 

Cheers,
