### ISSUE TITLE
More expansive "Allow" headers for CORS

### ISSUE THREAD

**Issue by dgruhl** [titi38/libnavajo#28]
It seems JQuery/Chrome is a little pushy. It wants Allow Headers and Allow Methods. I found adding 

```C++
      header += "Access-Control-Allow-Headers: X-Requested-With, Content-Type, Accept-Encoding, Accept-Language\r\n";
      header += "Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\r\n";
```
to WebServer.cc makes it happy.

**Comment by dgruhl** [comment]
PS - Optionally does it make sense to have a map of headers that gets dragged out of HttpResponse when the return message is sent?

**Comment by titi38** [comment]
Yes, I think it would make sense to have a whole class of specific' headers (with getter and setter) inside httpResponse... but it's a lot of work.

Meanwhile, I added 2 methods to the object httpResponse that will allow you to set some extra headers :
void addSpecificHeader(const char* header)
void addSpecificHeader(const std::string& header)

With the last commited version, you should now be able to do :
response->addSpecificHeader("Access-Control-Allow-Headers: X-Requested-With, Content-Type, Accept-Encoding, Accept-Language");
response->addSpecificHeader("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");

Cheers
