### ISSUE TITLE
Dynamic Repos

### ISSUE THREAD

**Issue by codesian** [titi38/libnavajo#29]
Sorry for this cuestion, maybe not an issue, part of my ignorance, but i can´t add a dynamic list of repos readed from a config file.

```
for (auto & path : statics) {
    		LocalRepository repo(config.get("www.statics."+ path + ".www",""), config.get("www.statics."+ path + ".path",""));
            webServer->addRepository(&repo);
 }
```
Im trying to add dynamic, pushing it to a vector and pass pointer to webserver:
quick and dirty:

```
std::vector<LocalRepository> repositories;

int i=0;
for (auto & path : statics) {
    		LocalRepository repo(config.get("www.statics."+ path + ".www",""), config.get("www.statics."+ path + ".path",""));
            repositories.push_back(repo);
            LocalRepository rarr = repositories.at(i);
    		webServer->addRepository(&rarr);
            i++;
}
```

Thanks and sorry

**Comment by titi38** [comment]
Hi,
You should use LocalRepository to add "Local" repositories (Local repositories should be precompiled with the "navajoPrecompiler" tool included, and then statically compiled with your project).
Have a look at the examples include in source tree.
Example1 will show you how local repositories work. Example 2 uses a dynamic repository (which may be more relevant to your needs)
Cheers,

**Comment by codesian** [comment]
Thanks!
