### ISSUE TITLE
Building with ustl

### ISSUE THREAD

**Issue by mingodad** [titi38/libnavajo#3]
Hello !
I did some changes to be able to compile this project with https://github.com/msharov/ustl it's on this fork https://github.com/mingodad/libnavajo , there is a codeblocks project file there for it.

Cheers !

**Comment by titi38** [comment]
Hello,
I will take a look. Thanks a lot.
Then, could I merge your changes into the main repository ?
Cheers,
Thierry Descombes

2016-01-10 1:01 GMT+01:00 Domingo Alvarez Duarte notifications@github.com:

**Comment by mingodad** [comment]
Sure this is what GPL/LGPL is for.

**Comment by titi38** [comment]
Hello,
I should have included all your change in the branch uSTL. (I've kept the
stl namespace default name...)
If you have an opportunity to test this version, could you confirm me that
it works ? Thanks a lot for your contribution !
Cheers

2016-01-10 11:04 GMT+01:00 Domingo Alvarez Duarte notifications@github.com
:

**Comment by mingodad** [comment]
Sadly it'll not work without using a different namespace because ustl still define some missing pieces using the std namespace.
Also your style is not consistent sometimes you use and don't use namespace prefix, after revising it I add all missing namespace prefixes and changed a bit the switch from std/ustl, you can see on my forked repository.
Cheers !

**Comment by titi38** [comment]
> Sadly it'll not work without using a different namespace because ustl
> still define some missing pieces using the std namespace.
> 
> It's a shame that a so-called STL compatible library don't even define the
> std namespace in the same way than the original one ! ;-)
> 
> Also your style is not consistent sometimes you use and don't use
> namespace prefix, after revising it I add all missing namespace prefixes
> and changed a bit the switch from std/ustl, you can see on my forked
> repository.
> 
> It's not a big deal, but you're right, I'll fix it. I used "using namespace
> std" for conveniance, but I don't like it (because there is a lot of
> declared statements in the namespace which can easily be in conflict with local ones).
> Could I use "STD" instead of "std" ? "**std**" or "std_compat" ? which one
> do you prefer ? (I don't like your "nw" so much ;-)

Cheers !

**Comment by mingodad** [comment]
Yes of course you can I used "nw" as a short for "namespace wrapper" and hopping that it would be unique enough to be easy mass replaced by anything else.
Cheers !
