### ISSUE TITLE
Can't build on Centos 7.6

### ISSUE THREAD

**Issue by jcourtat** [titi38/libnavajo#34]
[jcourtat@ns1 libnavajo] (master)$ mkdir build
[jcourtat@ns1 libnavajo] (master)$ cd build/
[jcourtat@ns1 build] (master)$ cmake3 ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jcourtat/dev/src/github.com/libnavajo/build
[jcourtat@ns1 build] (master)$ make
Scanning dependencies of target navajoPrecompiler
[  4%] Building CXX object CMakeFiles/navajoPrecompiler.dir/src/navajoPrecompiler.cc.o
[  8%] Linking CXX executable bin/navajoPrecompiler
[  8%] Built target navajoPrecompiler
Scanning dependencies of target navajoStatic
[ 12%] Building CXX object CMakeFiles/navajoStatic.dir/src/LocalRepository.cc.o
In file included from /home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/WebRepository.hh:17:0,
                 from /home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/LocalRepository.hh:17,
                 from /home/jcourtat/dev/src/github.com/libnavajo/src/LocalRepository.cc:23:
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh: In member function â€˜void HttpRequest::decodParams(const string&)â€™:
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:122:9: warning: â€˜autoâ€™ changes meaning in C++11; please remove it [-Wc++0x-compat]
         auto key        = theParam.substr(0,posEq);
         ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:122:14: error: â€˜keyâ€™ does not name a type
         auto key        = theParam.substr(0,posEq);
              ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:123:9: warning: â€˜autoâ€™ changes meaning in C++11; please remove it [-Wc++0x-compat]
         auto value      = theParam.substr(posEq+1);
         ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:123:14: error: â€˜valueâ€™ does not name a type
         auto value      = theParam.substr(posEq+1);
              ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:124:31: error: â€˜keyâ€™ was not declared in this scope
         if( parameters.count( key ) == 0 ) {
                               ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:125:29: error: â€˜valueâ€™ was not declared in this scope
           parameters[key] = value;
                             ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:127:11: warning: â€˜autoâ€™ changes meaning in C++11; please remove it [-Wc++0x-compat]
           auto arrayKey = key + "[]";
           ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:127:16: error: â€˜arrayKeyâ€™ does not name a type
           auto arrayKey = key + "[]";
                ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:128:33: error: â€˜arrayKeyâ€™ was not declared in this scope
           if( parameters.count( arrayKey ) == 1 ) {
                                 ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:129:43: error: â€˜valueâ€™ was not declared in this scope
             parameters[arrayKey] += "|" + value;
                                           ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:131:60: error: â€˜valueâ€™ was not declared in this scope
             parameters[arrayKey] = parameters[key] + "|" + value;
                                                            ^
/home/jcourtat/dev/src/github.com/libnavajo/include/libnavajo/HttpRequest.hh:133:29: error: â€˜valueâ€™ was not declared in this scope
           parameters[key] = value;
                             ^
make[2]: *** [CMakeFiles/navajoStatic.dir/src/LocalRepository.cc.o] Error 1
make[1]: *** [CMakeFiles/navajoStatic.dir/all] Error 2
make: *** [all] Error 2

**Comment by titi38** [comment]
Hi,
I have removed all the C++11 "auto" declarations, in order to improve to portability of the API. It should work now (git pull)
Cheers,
