### ISSUE TITLE
File corruption when using localRepository and a slow connection

### ISSUE THREAD

**Issue by jcourtat** [titi38/libnavajo#39]
Hello,
i'm trying to download a 10 MB file using localRepository object (no SSL).
If my wget client is on same subnet, the download is very fast and no corruption occurs.
If my wget client is on a distant network, with slow connection (300Kb/sec), then the corruption always happens.
Note that there are no corruption when using httpd between the same hosts, so the slow connection can't be considered as the corruptor.

regards

**Comment by jcourtat** [comment]
i'm adding some more info about my test. 
Centos 7.6, GCC 4.8.5
i compiled example/1_basic
[jcourtat@atlantique 1_basic] (master)$ ./example
[2021-03-17 09:24:50] >  WebServer: Service is starting !
[2021-03-17 09:25:42] >  Webserver: httpSend failed sending the page: docs/detector_1.0.10.tgz- err: Connection reset by peer

On the other host:
[kurt@kurt-B85M-HD3 ~]$  wget  http://192.168.1.97:8088/docs/detector_1.0.10.tgz
--2021-03-17 10:25:20--  http://192.168.1.97:8088/docs/detector_1.0.10.tgz
Connexion à 192.168.1.97:8088… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 9055640 (8,6M) []
Enregistre : «detector_1.0.10.tgz»

detector_1.0.10.tgz                         100%[===============================================================================>]   8,64M   419KB/s    ds 22s     

2021-03-17 10:25:42 (403 KB/s) - «detector_1.0.10.tgz» enregistré [9055640/9055640]

**Comment by jcourtat** [comment]
i found the issue, and now i'm fighting with git to propose a fix

**Comment by jcourtat** [comment]
i don't find how to rebase my forked repository against latest modification, so i'm not able to propose my fix, can you help ?

**Comment by titi38** [comment]
I gave you access to my respository. It will be easier and simpler ;-). Thank you for your contributions ! Cheers
