### ISSUE TITLE
Fermeture du serveur

### ISSUE THREAD

**Issue by tautret** [titi38/libnavajo#4]
Bonjour, je suis étudiant a la faculté de bordeaux et je souhaite utilisé libnavajo dans le cadre d'un projet scolaire. Je développe sur Mac OS X El Capitan.

Je me permets de vous contacter car, j'ai un problème sur la fermeture du port utilisé par libnavajo, a chaque fermeture du serveur, je suis obligé de fermer le serveur avec un "kill -9 pid".

Existe-il dans le code, une fonction pour fermer directement le serveur sans avoir a utiliser de kill.

**Comment by titi38** [comment]
Bonjour,
Je ne comprends pas bien votre question. Pourriez vous m'envoyer un exemple
complet ? Sur votre machine, les exemples qui sont disponibles avec la
librairie ne libèrent pas la socket lorsqu'ils ne terminent ?!? Merci

**Comment by tautret** [comment]
Merci d'avoir répondu,
Tout a fait lorsque je ferme le serveur via le terminal, le socket n'est pas libéré.

**Comment by titi38** [comment]
Qu'est ce qui vous fait dire que la socket n'est pas libéré ? quelle
commande ? Je n'ai rien observé de tel (et j'ai le même OS)

2016-02-09 18:22 GMT+01:00 tautret <notifications@github.com>:

**Comment by tautret** [comment]
Une fois que je ferme le serveur avec ctrl-z, et que je relance le ./example de suite voici les messages du terminale : 
[2016-02-10 13:11:25] >  WebServer: Service is starting !
[2016-02-10 13:11:25] >  WebServer : Init Failed ! (nbServerSock == 0): Address already in use
Je dois faire lsof -i :8080 et trouver le pid pour le kill.

**Comment by titi38** [comment]
... Ctrl-z n'est pas censé interrompre le processus !
Essais Ctrl-c ;-)

2016-02-10 14:12 GMT+01:00 tautret notifications@github.com:

**Comment by tautret** [comment]
Merci
