### ISSUE TITLE
Feature: DynamicPage HttpResponse send stream or file

### ISSUE THREAD

**Issue by Lexanius** [titi38/libnavajo#8]
Hello,

i try to send the binary data as a HttpResponse from a basic_stream (generated data) in cpp in a DynamicPage.
is there a simple way or must it convert it to a unsigned char *?

is there a simple way in Dynamic Pages to send Files? 
I only found the upload not the (dynamic) download.

Thx for helping

**Comment by titi38** [comment]
Hello Richard,

Until now, the only way to download a file is to fully load it in memory
and do something like this:

bool getPage(HttpRequest\* request, HttpResponse *response)
{
  unsigned char *yourBinaryContent;
  size_t yourBinaryContentLengthInBytes;
  // your custum method to load the file in memory:
  loadFile(&yourBinaryContent, &yourBinaryContentLengthInBytes);

  response->setMimeType("application/octet-stream"); // for example
  response->setContent (yourBinaryContent, yourBinaryContentLengthInBytes);

  return true;
}

Cheers,
Thierry Descombes

2016-06-17 4:48 GMT+02:00 Richard Stiller notifications@github.com:
