### ISSUE TITLE
Access POST request payload

### ISSUE THREAD

**Issue by spelle** [titi38/libnavajo#9]
Hello Thierry,

I'm currently building a RESTfull api for a small project we have here.

Building pages and adding them to the dynamic repository on-the-fly works well.

However, I can't figure out how to retrieve the payload of a POST request ?

Cheers,

**Comment by titi38** [comment]
Hi Sebastien,

You should be able to retrieve everything using the methods of the HttpRequest object.
( http://libnavajo.org/class_http_request.html )

POST and GET parameters can be browsed and retrieved in the same way. You can know how parameters have been passed using th  getRequestType() method. Returned type is HttpRequestMethod defined as follow:
typedef enum { UNKNOWN_METHOD = 0, GET_METHOD = 1, POST_METHOD = 2, PUT_METHOD = 3, DELETE_METHOD = 4 } HttpRequestMethod;

(I hope I will finally find some time to write a full real documentation soon... ;-)

Cheers

**Comment by spelle** [comment]
Hello Thierry,

I understand that parameters are read from the url : 
http://www.mydomain.com?parameter1=something&parameter2=somthing_else

Whereas, for RESTfull API, for POST rerquest, form data is passed as a JSON payload, within the request.

I just need to retrieve the payload as a string. Looks like this feature is not available, is it ?

**Comment by titi38** [comment]
Hi Sebastien,

All is available, and fully tested (even multipart content). POST and GET methods are supported.

If you use POST method the parameters are sent inside the http content response. 

Your GET request: 
http://www.mydomain.com?parameter1=something&parameter2=somthing_else

is equivalent to this POST request:

POST / HTTP/1.1
Host: www.mydomain.com
parameter1=something&parameter2=somthing_else

and znets decodes the parameters using the same mechanisms.  So, you can retrieve then using the same objects and methods either your form uses GET or POST method.

Cheers,

**Comment by spelle** [comment]
Hi Thierry,

Looks like we don't understand each other.. ^_^

Request       = Request-Line              ; Section 5.1
                        *(( general-header        ; Section 4.5
                         | request-header         ; Section 5.3
                         | entity-header ) CRLF)  ; Section 7.1
                        CRLF
                        [ message-body ]          ; Section 4.3

I do not need to retrieve parameters passed within the URL.

I need to retrieve the message-body of a request. Any ideas of how to achieve his ?

Cheers,

**Comment by titi38** [comment]
Hi Sebastien,

Ok,  we'll get there ;-)
So right now, the "payload" of your POST request should be formatted like a html FORM element using method="POST".  
Thus, libNavajo only support the "application/x-www-form-urlencoded" Content-Type, and the message body should be a list of "key-value" pair...

Couldn't you pass something like:
myjson=YOUR_JSON

libNavajo currently de-allocates the http payload, after trying to decode parameters. I would try and think a way to access to it through the httpRequest object...

Cheers,

**Comment by spelle** [comment]
Hi Thierry,

I think, url-encoded is not compatible with RESTfull API. I will check this.

I'm almost done with adding it in libNavajo. May I propose a merge request ?

Cheers,

**Comment by titi38** [comment]
Okay, and yes of course !
Could you send me an example of the full http request (with header and contents) generated by your RESTfull API  ? Thanks
Cheers

**Comment by spelle** [comment]
I made a merge request aside this issue. I let you review it and let me know.

For a POST request :
`$ curl -v -H "Content-Type: application/json" -X POST -d '{"creationDate":"2016-Sep-30 00:00:00","startDateMonthOffset":"1","endDateMonthOffset":"9"}' http://localhost:8080/keySet/generate`

For a GET request :
`curl -v http://localhost:8080/keySet/83aeefec-5615-4327-a38e-d9106f775ec4
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 8080 (#0)
  > GET /keySet/83aeefec-5615-4327-a38e-d9106f775ec4 HTTP/1.1
  > Host: localhost:8080
  > User-Agent: curl/7.47.0
  > Accept: _/_
  > 
  < HTTP/1.1 200 OK
  < Date: Fri, 16 Sep 2016 21:06:40 GMT
  < Server: libNavajo/1.2.0
  < Accept-Ranges: bytes
  < Connection: Keep-Alive
  < Content-Type: 
  < Content-Length: 206
  < 
  [
  {
      "hksCreationDate" : "2016-Sep-30 00:00:00",
      "hksId" : "83aeefec-5615-4327-a38e-d9106f775ec4",
      "hksValidityEndDate" : "2017-Jun-01 00:00:00",
      "hksValidityStartDate" : "2016-Oct-01 00:00:00"
  }
  ]
- Connection #0 to host localhost left intact`

I think response's json payload is not conform yet.. I'm on it... I use JsonCpp for this.

Cheers,

**Comment by titi38** [comment]
Hi Sebastien,
It's fine ! Thanks.
Maybe, I will modify later to also add support for others Content-Type. (It seems that every kind of content is possible...)
Cheers,
